# Generated by Django 3.2.13 on 2022-05-11 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.PositiveSmallIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('memo', models.CharField(max_length=128, null=True)),
            ],
            options={
                'db_table': 'studentdetail',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=32)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.class')),
                ('detail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project.studentdetail')),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
