# Generated by Django 3.2.13 on 2022-05-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_student_studentdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sname',
            field=models.CharField(max_length=48),
        ),
    ]
