# Generated by Django 3.2.13 on 2022-05-12 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetail',
            name='email',
        ),
    ]
