# Generated by Django 3.2.13 on 2022-05-12 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_student_cid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='project.class'),
        ),
    ]
