# Generated by Django 3.2.13 on 2022-05-13 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_teacher'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='teacher',
            table='teacher',
        ),
    ]
